version: '3.7'

services:
  app:
    build: ./
    container_name: wetbulb-warnings-app
    command: streamlit run wetbulb_warnings.py
    volumes:
      - .:/app
    ports:
      - 8501:8501
    image: wetbulb-warnings:latest
